// <auto-generated />
namespace Bai_Tap_Lon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class thongtinkhachhang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thongtinkhachhang));
        
        string IMigrationMetadata.Id
        {
            get { return "202105040315341_thongtinkhachhang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
